## Environment configuration for the framework
## Change values here instead of hardcoding inside test classes

base.url=https://www.saucedemo.com/
browser=chrome
implicit.wait=10
explicit.wait=15
headless=false

## Standard SauceDemo test credentials
valid.username=standard_user
locked.username=locked_out_user
valid.password=secret_sauce
invalid.password=wrong_password
